### ISSUE TITLE
Dev build running into multiple issues. 

### ISSUE THREAD

**Issue by noonosh** [unfoldadmin/turbo#33]
I was playing around with django-unfold and I quite like it! However, coming across this turbo repo, I was able to fall into some issues.

### **docker compose** VS **docker-compose**
First of all _docker_ command on Mac seems like does not have _compose_ command available, so it's _docker-compose_ that needs to be run instead.

![Warp_LDnEw7EI_11_2024](https://github.com/user-attachments/assets/83069c3d-d73c-44fa-81c8-7335cd8897ae)

### Posgresql instructions

- Seems unclear to set up postgresql db as the readme doesn't state what is to be used as creds – default _postgres_ user is run on docker compose up command.
- then, this command, that i have not solved yet:

![Warp_a3hdkYer_11_2024](https://github.com/user-attachments/assets/98cd8032-e9c6-4aa9-92b2-6fa8c09a0889)

altough permission denied error is a common warning to fix, what seems confusing to me is that all apps from docker-compose.yaml – db, api, web seem to be second version of themselves – api-1, db-1, web-1 – correct me if wrong.

What's the easiest spin up of this turbo repo without extra work?

**Comment by lukasvinclav** [comment]
1. make sure that you are using most recent version of Docker. Instead of `docker-compose` it is using `docker compose` (without hyphen)
2. regarding postgres, there should be no extra steps to configure it. Maybe it is because you are using older version of Docker on Mac. Sometimes playing with "Choose file sharing implementation for your containers" in your Docker settings helps.
